[package]
name = "exercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
target = "x86_64-unknown-linux-gnu"

[dependencies]
stdext = "0.3.1"
backtrace = "0.3.65"