diff a/user/Makefile b/user/Makefile	(rejected hunks)
@@ -13,8 +17,9 @@ elf: $(APPS)
 	@python3 build.py
 
 binary: elf
+	@echo $(ELFS)
 	@$(foreach elf, $(ELFS), $(OBJCOPY) $(elf) --strip-all -O binary $(patsubst $(TARGET_DIR)/%, $(TARGET_DIR)/%.bin, $(elf));)
-
+#rust-objcopy --strip-all target/riscv64gc-unknown-none-elf/release/os -O binary target/riscv64gc-unknown-none-elf/release/os.bin
 build: binary
 
 clean:
